
export const FACES = [
{ f: 'AM31AFS.jpg', n: 'AM31NES.jpg' },
{ f: 'AM34AFS.jpg', n: 'AM34NES.jpg' },
{ f: 'AM35AFS.jpg', n: 'AM35NES.jpg' },
{ f: 'AM10AFS.jpg', n: 'AM10NES.jpg' },
{ f: 'AM17AFS.jpg', n: 'AM17NES.jpg' },
{ f: 'AM22AFS.jpg', n: 'AM22NES.jpg' },
{ n: 'AM23NES.jpg', f: 'AM23AFS.jpg' },
{ f: 'AF30AFS.jpg', n: 'AF30NES.jpg' },
{ f: 'AF32AFS.jpg', n: 'AF32NES.jpg' },
{ f: 'AM09AFS.jpg', n: 'AM09NES.jpg' },
{ f: 'AF14AFS.jpg', n: 'AF14NES.jpg' },
{ f: 'AF19AFS.jpg', n: 'AF19NES.jpg' },
{ f: 'AF22AFS.jpg', n: 'AF22NES.jpg' },
{ f: 'AF24AFS.jpg', n: 'AF24NES.jpg' },
{ f: '217Fcrop.jpg', n: '217Ncrop.jpg' },
{ f: 'AF01AFS.jpg', n: 'AF01NES.jpg' },
{ f: 'AF13AFS.jpg', n: 'AF13NES.jpg' },
{ f: '207Fcrop.jpg', n: '207Ncrop.jpg' },
{ f: '208Fcrop.jpg', n: '208Ncrop.jpg' },
{ f: '213Fcrop.jpg', n: '213Ncrop.jpg' } ];


export const WORDS = [
    { f: 'trauma', n: 'runner' },
    { f: 'pollute', n: 'ketchup' },
    { f: 'massacre', n: 'windmill' },
    { f: 'unfaithful', n: 'skyscraper' },
    { f: 'noose', n: 'jelly' },
    { f: 'torture', n: 'volcano' },
    { f: 'mutilate', n: 'radiator' },
    { f: 'assassin', n: 'umbrella' },
    { f: 'ambulance', n: 'sheltered' },
    { f: 'terrified ', n: 'appliance' },
    { f: 'bloody', n: 'locker' },
    { f: 'neglect ', n: 'lantern' },
    { f: 'fearful', n: 'cabinet' },
    { f: 'cruel', n: 'stove' },
    { f: 'horror', n: 'violin' },
    { f: 'hatred', n: 'sphere' },
    { f: 'jail', n: 'bowl' },
    { f: 'panic ', n: 'salad' },
    { f: 'nervous', n: 'prairie' },
    { f: 'devil', n: 'bench' },
    { f: 'cliff', n: 'tower' },
    { f: 'violent', n: 'stomach' },
    { f: 'rejected', n: 'reserved' },
    { f: 'bomb', n: 'tool' },
    { f: 'sin', n: 'hat' },
    { f: 'afraid', n: 'yellow' },
    { f: 'danger', n: 'column' },
    { f: 'hospital', n: 'machine' },
    { f: 'fear', n: 'farm' },
    { f: 'alone', n: 'table' }
];
